### ISSUE TITLE
"Uncaught SyntaxError: Unexpected reserved word" is reported at getColors.js:5 

### ISSUE THREAD

**Issue by bin787** [mdn/js-examples#11]
with Chrome Version 88.0.4324.182 (Official Build) (32-bit), https://mdn.github.io/js-examples/modules/top-level-await/ fails to load as expected with the error as title reported. Same with Fire Fox 85.0.2 (64-bit).

Looks like "export default await colors;" has some issue with the usage of await here.

can you please have a look?

**Comment by chrisdavidmills** [comment]
@Rumyra this example now seems to be giving the same error as it did a little while ago. Can you have a quick look? Many thanks.

**Comment by bin787** [comment]
I just cross-checked browser compatibility and found that neither 88.0.4324.182 (Official Build) (32-bit) nor FireFox 85.0.2 (64-bit) support the top level await yet. I think this issue can be closed.
thanks for your attention.

**Comment by chrisdavidmills** [comment]
I think it may well need attention. I'm using Firefox Nightly and have top-level await enabled, and it is still erroring for me.

**Comment by chrisdavidmills** [comment]
The error I get is "Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data".

I think we got this once before and it was something simple like a path issue...

**Comment by Rumyra** [comment]
Yes it's a path issue again - running the repo locally and viewing the live sample on gh have different paths... I'm just having a think, but leave it with me - it's fixable 👍 thanks @chrisdavidmills

**Comment by Rumyra** [comment]
OK fix works in Chrome & FF (with pref) for me so I'm going to keep this issue closed - lmk if there's any problems 👍

**Comment by bin787** [comment]
@chrisdavidmills and @Rumyra thanks for prompt actions though the actual issue is different from the one originally reported.
