### ISSUE TITLE
Call function in js module

### ISSUE THREAD

**Issue by vankhanhpr** [mdn/js-examples#13]
How  to call a function in the HTML after import js module to htlm file, help me please!

**Comment by schalkneethling** [comment]
> How to call a function in the HTML after import js module to htlm file, help me please!

Hey @vankhanhpr, these repositories are not a place to ask for help with coding problems. For this, I recommend you open a [thread on our Discourse forums](https://discourse.mozilla.org/c/mdn/236) or [StackOverflow](https://stackoverflow.com).
