### ISSUE TITLE
The module example fails due to CORS

### ISSUE THREAD

**Issue by YagaoDirac** [mdn/js-examples#14]
I tried modules/basic-modules/
Nothing displayed in the browser. In F12 console, I see
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///E:/js%20examples%20from%20mdn/js-examples-master/modules/basic-modules/main.js. (Reason: CORS request not http).
2
Module source URI is not allowed in this document: “file:///E:/js%20examples%20from%20mdn/js-examples-master/modules/basic-modules/main.js”.

**Comment by jesperp** [comment]
You need to load your files through a web server, not directly from the file system (e.g http-server). Also make sure that your web server sets the correct mime type for js files.

**Comment by schalkneethling** [comment]
Hey @YagaoDirac, as @jesperp states, you must load this using a web server. There are many options for this. One of those is lite-server, which you can find on [npmjs.com](https://www.npmjs.com/package/lite-server).

In the future, we recommend that you use either our [Discourse forums](https://discourse.mozilla.org/c/mdn/236) or [StackOverflow](https://stackoverflow.com) for help with code.
