### ISSUE TITLE
Top Level Await examples do not have  await code 

### ISSUE THREAD

**Issue by xkeshav** [mdn/js-examples#28]
under the **top level await** example folder, the code in *main.js* file  is similar to **dynamic module imports** example folder *main.js* file content, 

There is no example of usage of `await` syntax.

Cheke this file

https://github.com/mdn/js-examples/blob/main/module-examples%2Ftop-level-await%2Fmain.js

this code is similar to the previous example (dynamic module import) file

https://github.com/mdn/js-examples/blob/main/module-examples%2Fdynamic-module-imports%2Fmain.js

**Comment by Chay2203** [comment]
Hey, I would love to work on this issue, can you assign me!?

**Comment by xkeshav** [comment]
Hey, This has been fixed by me already.

**Comment by Chay2203** [comment]
Ohh great @xkeshav!

**Comment by bsmth** [comment]
Closing this one, see the linked PR for details. Thank you :)
